'use server';

import { Resend } from 'resend';
import { BRAND } from '@/lib/constants/brand';
import { BELT_DISPLAY, type BeltLevel } from '@/lib/constants/belts';

const resend = new Resend(process.env.RESEND_API_KEY);

interface SessionEmailData {
  studentName: string;
  studentEmail: string;
  portalToken: string;
  coachName: string;
  sessionDate: string;
  mission: string;
  status: string;
  coachFeedback: string;
  homework: string;
  whatsNext: string;
  beltLevel: BeltLevel;
  /** student_session_results.id — used to deep-link directly to this survey. */
  sessionResultId?: string;
  /** student_session_results.feedback_token — when set, sends Leads to the
   *  standalone /feedback/[token] page instead of the full portal. */
  feedbackToken?: string;
  /** Whether the student has ANY course access (white_belt OR yellow_belt).
   *  Leads = false → standalone feedback page. Members = true → full portal. */
  studentHasCourseAccess?: boolean;
}

export async function sendSessionEmail(data: SessionEmailData): Promise<{ success: boolean; error?: string }> {
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000';
  const portalUrl = `${appUrl}/portal/${data.portalToken}`;
  const belt = BELT_DISPLAY[data.beltLevel];

  // Route Leads (no course access) to the standalone /feedback/[token]
  // page so they never see the full portal. Members keep the full
  // portal experience that lands on the feedback tab.
  const useStandalone = data.feedbackToken && data.studentHasCourseAccess === false;
  const feedbackUrl = useStandalone
    ? `${appUrl}/feedback/${data.feedbackToken}`
    : data.sessionResultId
      ? `${portalUrl}?tab=feedback&survey=${data.sessionResultId}`
      : `${portalUrl}?tab=feedback`;

  try {
    await resend.emails.send({
      from: process.env.RESEND_FROM_EMAIL || 'The Surf Sequence <onboarding@resend.dev>',
      to: data.studentEmail,
      subject: `Your session report from ${data.coachName}`,
      html: buildEmailHtml({ ...data, portalUrl, feedbackUrl, beltColor: belt?.color || '#1A1A2E' }),
    });
    return { success: true };
  } catch (err: any) {
    console.error('Email send failed:', err.message);
    return { success: false, error: err.message };
  }
}

// ─── Coach invite email — sent on coach creation OR re-send ──────────
//
// Replaces Supabase's default invite email so we control the branding,
// language and the explicit credentials block ("your email + click to
// set password"). The magic link is generated by the caller via
// supabase.auth.admin.generateLink({ type: 'invite' }) so we can embed
// it in our own HTML.

interface CoachInviteEmailData {
  toEmail: string;
  firstName: string;
  role: 'admin' | 'coordinator' | 'coach' | 'assistant';
  academyName: string;
  /** The magic link from Supabase generateLink — clicking it sets a session and lands on /set-password. */
  inviteLink: string;
  /** Optional — when re-sending we surface that the invite was already sent before. */
  isResend?: boolean;
}

export async function sendCoachInviteEmail(
  data: CoachInviteEmailData,
): Promise<{ success: boolean; error?: string }> {
  try {
    await resend.emails.send({
      from: process.env.RESEND_FROM_EMAIL || 'The Surf Sequence <onboarding@resend.dev>',
      to: data.toEmail,
      subject: data.isResend
        ? `Reminder — activate your ${BRAND.name} account`
        : `Welcome to ${BRAND.name} — activate your account`,
      html: buildCoachInviteHtml(data),
    });
    return { success: true };
  } catch (err: any) {
    console.error('Coach invite email send failed:', err.message);
    return { success: false, error: err.message };
  }
}

// Minimal HTML escape — protects against XSS / accidental tag injection
// when user-supplied strings (firstName, academyName, email) are
// embedded into the email HTML. Resend treats `html` as raw HTML.
function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function buildCoachInviteHtml(data: CoachInviteEmailData): string {
  const roleLabel =
    data.role === 'coordinator'
      ? 'Academy Coordinator'
      : data.role === 'assistant'
      ? 'Assistant Coach'
      : data.role === 'admin'
      ? 'Admin'
      : 'Coach';

  const firstName = escapeHtml(data.firstName);
  const academyName = escapeHtml(data.academyName);
  const toEmail = escapeHtml(data.toEmail);
  // inviteLink is a Supabase-generated URL — safe to embed in href but
  // escape just for &/" sanity if any query param ever contained them.
  const inviteLink = escapeHtml(data.inviteLink);

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#F9FAFB;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <div style="max-width:520px;margin:0 auto;padding:24px 16px;">
    <!-- Header -->
    <div style="background:${BRAND.colors.navy};border-radius:12px 12px 0 0;padding:28px 24px;text-align:center;">
      <h1 style="margin:0;color:white;font-size:22px;font-weight:700;letter-spacing:-0.01em;">${BRAND.name}</h1>
      <p style="margin:6px 0 0;color:${BRAND.colors.cyan};font-size:12px;letter-spacing:0.02em;">${BRAND.tagline}</p>
    </div>

    <!-- Body -->
    <div style="background:white;padding:28px 24px;border-radius:0 0 12px 12px;border:1px solid #E5E7EB;border-top:none;">
      <p style="margin:0 0 16px;font-size:15px;color:#111827;">
        Hi <strong>${firstName}</strong>,
      </p>
      <p style="margin:0 0 20px;font-size:14px;color:#374151;line-height:1.6;">
        ${data.isResend ? 'A reminder — you were' : 'You\'ve been'} added to
        <strong>${academyName}</strong> on ${BRAND.name} as
        <strong>${roleLabel}</strong>.
      </p>

      <!-- Credentials block -->
      <div style="background:#F9FAFB;border-radius:8px;padding:16px;margin-bottom:20px;border:1px solid #E5E7EB;">
        <p style="margin:0 0 6px;font-size:11px;color:#6B7280;text-transform:uppercase;letter-spacing:0.05em;font-weight:600;">Your login email</p>
        <p style="margin:0;font-size:14px;color:#111827;font-weight:600;font-family:monospace;">${toEmail}</p>
      </div>

      <p style="margin:0 0 16px;font-size:14px;color:#374151;line-height:1.6;">
        Click the button below to activate your account, set your password,
        and access your dashboard.
      </p>

      <!-- CTA: Activate account -->
      <a href="${inviteLink}" style="display:block;background:${BRAND.colors.navy};color:white;text-align:center;padding:14px;border-radius:8px;text-decoration:none;font-size:14px;font-weight:600;">
        Activate my account &amp; set password
      </a>

      <p style="margin:14px 0 0;font-size:11px;color:#9CA3AF;text-align:center;line-height:1.5;">
        This link is one-time use and expires in 24 hours.<br/>
        If you didn't expect this email, you can safely ignore it.
      </p>
    </div>

    <!-- Footer -->
    <p style="text-align:center;font-size:11px;color:#9CA3AF;margin:16px 0 0;">
      ${BRAND.name}® · ${BRAND.tagline}
    </p>
  </div>
</body>
</html>`;
}

// ─── Password reset email — branded recovery link ────────────────────

interface PasswordResetEmailData {
  toEmail: string;
  firstName: string;
  /** Supabase recovery link (generateLink type:'recovery') — exchanges
   * the code for a session and lands on /set-password via callback next. */
  resetLink: string;
}

export async function sendPasswordResetEmail(
  data: PasswordResetEmailData,
): Promise<{ success: boolean; error?: string }> {
  try {
    await resend.emails.send({
      from: process.env.RESEND_FROM_EMAIL || 'The Surf Sequence <onboarding@resend.dev>',
      to: data.toEmail,
      subject: `Reset your ${BRAND.name} password`,
      html: buildPasswordResetHtml(data),
    });
    return { success: true };
  } catch (err: any) {
    console.error('Password reset email send failed:', err.message);
    return { success: false, error: err.message };
  }
}

function buildPasswordResetHtml(data: PasswordResetEmailData): string {
  const firstName = escapeHtml(data.firstName);
  const toEmail = escapeHtml(data.toEmail);
  const resetLink = escapeHtml(data.resetLink);

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#F9FAFB;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <div style="max-width:520px;margin:0 auto;padding:24px 16px;">
    <div style="background:${BRAND.colors.navy};border-radius:12px 12px 0 0;padding:28px 24px;text-align:center;">
      <h1 style="margin:0;color:white;font-size:22px;font-weight:700;letter-spacing:-0.01em;">${BRAND.name}</h1>
      <p style="margin:6px 0 0;color:${BRAND.colors.cyan};font-size:12px;letter-spacing:0.02em;">${BRAND.tagline}</p>
    </div>
    <div style="background:white;padding:28px 24px;border-radius:0 0 12px 12px;border:1px solid #E5E7EB;border-top:none;">
      <p style="margin:0 0 16px;font-size:15px;color:#111827;">
        Hi <strong>${firstName}</strong>,
      </p>
      <p style="margin:0 0 20px;font-size:14px;color:#374151;line-height:1.6;">
        We received a request to reset the password for your ${BRAND.name} account.
      </p>
      <div style="background:#F9FAFB;border-radius:8px;padding:16px;margin-bottom:20px;border:1px solid #E5E7EB;">
        <p style="margin:0 0 6px;font-size:11px;color:#6B7280;text-transform:uppercase;letter-spacing:0.05em;font-weight:600;">Account email</p>
        <p style="margin:0;font-size:14px;color:#111827;font-weight:600;font-family:monospace;">${toEmail}</p>
      </div>
      <p style="margin:0 0 16px;font-size:14px;color:#374151;line-height:1.6;">
        Click the button below to set a new password.
      </p>
      <a href="${resetLink}" style="display:block;background:${BRAND.colors.navy};color:white;text-align:center;padding:14px;border-radius:8px;text-decoration:none;font-size:14px;font-weight:600;">
        Reset my password
      </a>
      <p style="margin:14px 0 0;font-size:11px;color:#9CA3AF;text-align:center;line-height:1.5;">
        This link is one-time use and expires in 1 hour.<br/>
        If you didn't request a password reset, you can safely ignore this email.
      </p>
    </div>
    <p style="text-align:center;font-size:11px;color:#9CA3AF;margin:16px 0 0;">
      ${BRAND.name}® · ${BRAND.tagline}
    </p>
  </div>
</body>
</html>`;
}

function buildEmailHtml(data: SessionEmailData & { portalUrl: string; feedbackUrl: string; beltColor: string }): string {
  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#F9FAFB;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <div style="max-width:520px;margin:0 auto;padding:24px 16px;">
    <!-- Header -->
    <div style="background:${BRAND.colors.navy};border-radius:12px 12px 0 0;padding:24px;text-align:center;">
      <h1 style="margin:0;color:white;font-size:20px;font-weight:700;">The Surf Sequence</h1>
      <p style="margin:4px 0 0;color:${BRAND.colors.gold};font-size:12px;">${BRAND.tagline}</p>
    </div>

    <!-- Body -->
    <div style="background:white;padding:24px;border-radius:0 0 12px 12px;border:1px solid #E5E7EB;border-top:none;">
      <p style="margin:0 0 16px;font-size:15px;color:#111827;">
        Hi <strong>${data.studentName}</strong>,
      </p>
      <p style="margin:0 0 20px;font-size:14px;color:#374151;line-height:1.5;">
        Here is your session report from <strong>${data.coachName}</strong>.
      </p>

      <!-- Session card -->
      <div style="background:#F9FAFB;border-radius:8px;padding:16px;margin-bottom:20px;">
        <div style="display:flex;justify-content:space-between;margin-bottom:8px;">
          <span style="font-size:12px;color:#6B7280;">Date</span>
          <span style="font-size:13px;color:#111827;font-weight:500;">${new Date(data.sessionDate).toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' })}</span>
        </div>
        <div style="margin-bottom:8px;">
          <span style="font-size:12px;color:#6B7280;">Mission</span>
          <p style="margin:4px 0 0;font-size:14px;color:#111827;font-weight:600;">${data.mission}</p>
        </div>
        <div style="display:flex;justify-content:space-between;margin-bottom:8px;">
          <span style="font-size:12px;color:#6B7280;">Status</span>
          <span style="font-size:13px;color:#111827;font-weight:500;text-transform:capitalize;">${data.status.replace('_', ' ')}</span>
        </div>
      </div>

      <!-- Feedback -->
      <div style="margin-bottom:16px;">
        <p style="font-size:12px;color:#6B7280;margin:0 0 4px;">Coach Feedback</p>
        <p style="font-size:14px;color:#374151;line-height:1.5;margin:0;">${data.coachFeedback}</p>
      </div>

      <!-- Homework -->
      <div style="background:#FFF7ED;border-left:3px solid ${BRAND.colors.gold};padding:12px;border-radius:0 8px 8px 0;margin-bottom:16px;">
        <p style="font-size:11px;color:#92400E;margin:0 0 4px;font-weight:600;text-transform:uppercase;letter-spacing:0.5px;">Your Homework</p>
        <p style="font-size:14px;color:#78350F;margin:0;font-weight:500;">${data.homework}</p>
      </div>

      <!-- What's Next -->
      <div style="margin-bottom:24px;">
        <p style="font-size:12px;color:#6B7280;margin:0 0 4px;">Next Recommended Focus</p>
        <p style="font-size:14px;color:#111827;font-weight:500;margin:0;">${data.whatsNext}</p>
      </div>

      <!-- CTA: Rate Session -->
      <a href="${data.feedbackUrl}" style="display:block;background:${BRAND.colors.navy};color:white;text-align:center;padding:14px;border-radius:8px;text-decoration:none;font-size:14px;font-weight:600;">
        Rate Your Session &amp; Coach &#9733;
      </a>

      <p style="margin:16px 0 0;font-size:12px;color:#9CA3AF;text-align:center;">
        Your feedback helps us improve. Takes 30 seconds.
      </p>

      <!-- Secondary CTA: Dashboard -->
      <a href="${data.portalUrl}" style="display:block;text-align:center;padding:10px;font-size:13px;color:${BRAND.colors.navy};text-decoration:none;font-weight:500;margin-top:8px;">
        View your full training dashboard &rarr;
      </a>
    </div>

    <!-- Footer -->
    <p style="text-align:center;font-size:11px;color:#9CA3AF;margin:16px 0 0;">
      The Surf Sequence® · Evolve through play
    </p>
  </div>
</body>
</html>`;
}
