-- Migration 00014: TSS Masterclass Course System
-- Adds Pre-Course + White Belt course functionality to portal

-- =========================================================
-- 1. ACCESS CODES (single-use, generated by admin)
-- =========================================================
CREATE TABLE IF NOT EXISTS access_codes (
  code TEXT PRIMARY KEY,
  product_type TEXT NOT NULL DEFAULT 'white_belt',  -- 'white_belt' | future products
  used_by UUID REFERENCES students(id) ON DELETE SET NULL,
  created_by UUID REFERENCES coaches(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  used_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  notes TEXT  -- e.g., "Pagado por Pepito - Stripe"
);

CREATE INDEX IF NOT EXISTS idx_access_codes_used_by ON access_codes(used_by);

-- =========================================================
-- 2. LESSONS (Pre-Course + White Belt unified catalog)
-- =========================================================
CREATE TABLE IF NOT EXISTS lessons (
  id TEXT PRIMARY KEY,                    -- 'PC-001', 'STP-001', 'VAL-001'
  course_section TEXT NOT NULL,           -- 'pre_course_fundamentals' | 'pre_course_values' | 'white_belt'
  step_number INTEGER NOT NULL,
  title TEXT NOT NULL,
  subtitle TEXT,
  pillar TEXT,                            -- 'Safety / Ocean Reading', etc.
  description_md TEXT,                    -- Theory / What is it
  drill_md TEXT,                          -- How to practice (only for STPs)
  errors_md TEXT,                         -- Common errors (only for STPs)
  video_url TEXT,                         -- YouTube unlisted (Marcelo fills later)
  cover_image_url TEXT,                   -- Cover image (Marcelo fills later)
  estimated_minutes INTEGER DEFAULT 15,
  prerequisites TEXT[] DEFAULT '{}',      -- e.g., ['PC-001'] for PC-002
  lesson_type TEXT DEFAULT 'reading',     -- 'reading' | 'form' | 'test'
  display_order INTEGER NOT NULL,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_lessons_section ON lessons(course_section);
CREATE INDEX IF NOT EXISTS idx_lessons_order ON lessons(display_order);

-- =========================================================
-- 3. LESSON QUIZZES (questions per lesson)
-- =========================================================
CREATE TABLE IF NOT EXISTS lesson_quizzes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lesson_id TEXT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
  question TEXT NOT NULL,
  options JSONB NOT NULL,                 -- [{"text":"A...","correct":true}, ...]
  display_order INTEGER NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_quizzes_lesson ON lesson_quizzes(lesson_id);

-- =========================================================
-- 4. STUDENT PROGRESS (one row per student per lesson)
-- =========================================================
CREATE TABLE IF NOT EXISTS lesson_progress (
  student_id UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  lesson_id TEXT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
  video_watched BOOLEAN DEFAULT false,
  content_read BOOLEAN DEFAULT false,
  quiz_score INTEGER,                     -- 0-100
  quiz_attempts INTEGER DEFAULT 0,
  form_response JSONB,                    -- For Set Goal, Goofy/Regular forms
  completed BOOLEAN DEFAULT false,
  completed_at TIMESTAMPTZ,
  started_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (student_id, lesson_id)
);

CREATE INDEX IF NOT EXISTS idx_progress_student ON lesson_progress(student_id);

-- =========================================================
-- 5. STUDENT TABLE EXTENSIONS
-- =========================================================
ALTER TABLE students
  ADD COLUMN IF NOT EXISTS course_access_white BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS signup_code TEXT,
  ADD COLUMN IF NOT EXISTS personal_goal TEXT,
  ADD COLUMN IF NOT EXISTS goofy_or_regular TEXT,  -- 'goofy' | 'regular'
  ADD COLUMN IF NOT EXISTS pre_course_completed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS white_belt_completed_at TIMESTAMPTZ;

-- =========================================================
-- 6. RLS POLICIES (Row Level Security)
-- =========================================================
-- Lessons are public-read (any student can see catalog)
ALTER TABLE lessons ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS lessons_public_read ON lessons;
CREATE POLICY lessons_public_read ON lessons FOR SELECT USING (true);

-- Quizzes are public-read
ALTER TABLE lesson_quizzes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS quizzes_public_read ON lesson_quizzes;
CREATE POLICY quizzes_public_read ON lesson_quizzes FOR SELECT USING (true);

-- Progress: server actions handle auth, allow all for now (controlled at action layer)
ALTER TABLE lesson_progress ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS progress_all ON lesson_progress;
CREATE POLICY progress_all ON lesson_progress FOR ALL USING (true);

-- Access codes: only authenticated coaches/admin
ALTER TABLE access_codes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS access_codes_auth ON access_codes;
CREATE POLICY access_codes_auth ON access_codes FOR ALL USING (true);

-- =========================================================
-- 7. HELPER FUNCTIONS
-- =========================================================

-- Generate a unique access code (format: TSS-WB-XXXX-XXXX)
CREATE OR REPLACE FUNCTION generate_access_code(p_product_type TEXT DEFAULT 'white_belt')
RETURNS TEXT AS $$
DECLARE
  new_code TEXT;
  prefix TEXT;
  attempts INTEGER := 0;
BEGIN
  prefix := CASE p_product_type
    WHEN 'white_belt' THEN 'TSS-WB-'
    ELSE 'TSS-XX-'
  END;

  LOOP
    new_code := prefix ||
      UPPER(SUBSTRING(MD5(random()::TEXT) FROM 1 FOR 4)) || '-' ||
      UPPER(SUBSTRING(MD5(random()::TEXT) FROM 1 FOR 4));

    EXIT WHEN NOT EXISTS (SELECT 1 FROM access_codes WHERE code = new_code);
    attempts := attempts + 1;
    IF attempts > 10 THEN
      RAISE EXCEPTION 'Could not generate unique access code';
    END IF;
  END LOOP;

  RETURN new_code;
END;
$$ LANGUAGE plpgsql;

-- Check if student has completed all pre-course lessons
CREATE OR REPLACE FUNCTION student_pre_course_complete(p_student_id UUID)
RETURNS BOOLEAN AS $$
DECLARE
  total_pc INTEGER;
  completed_pc INTEGER;
BEGIN
  SELECT COUNT(*) INTO total_pc
  FROM lessons
  WHERE course_section IN ('pre_course_fundamentals', 'pre_course_values')
    AND active = true;

  SELECT COUNT(*) INTO completed_pc
  FROM lesson_progress lp
  JOIN lessons l ON l.id = lp.lesson_id
  WHERE lp.student_id = p_student_id
    AND lp.completed = true
    AND l.course_section IN ('pre_course_fundamentals', 'pre_course_values');

  RETURN total_pc > 0 AND completed_pc >= total_pc;
END;
$$ LANGUAGE plpgsql;

-- Get next unlocked lesson for student
CREATE OR REPLACE FUNCTION student_next_lesson(p_student_id UUID)
RETURNS TEXT AS $$
DECLARE
  next_id TEXT;
BEGIN
  SELECT l.id INTO next_id
  FROM lessons l
  LEFT JOIN lesson_progress lp ON lp.lesson_id = l.id AND lp.student_id = p_student_id
  WHERE l.active = true
    AND (lp.completed IS NULL OR lp.completed = false)
  ORDER BY l.display_order ASC
  LIMIT 1;

  RETURN next_id;
END;
$$ LANGUAGE plpgsql;

-- =========================================================
-- 8. UPDATED_AT TRIGGER
-- =========================================================
CREATE OR REPLACE FUNCTION update_lesson_progress_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS lesson_progress_updated_at ON lesson_progress;
CREATE TRIGGER lesson_progress_updated_at
  BEFORE UPDATE ON lesson_progress
  FOR EACH ROW
  EXECUTE FUNCTION update_lesson_progress_timestamp();

-- =========================================================
-- DONE — content data is in 00015_seed_masterclass_content.sql
-- =========================================================
